version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  ruby:
    build:
      context: ./ruby
      dockerfile: ../docker/ruby/Dockerfile
    volumes:
      - ./ruby:/usr/src/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "8000:3000"
    depends_on:
    - db
  web:
    build:
      context: ./web
      dockerfile: ../docker/web/Dockerfile
    volumes:
      - ./web:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true